name: Verify

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  repository-initialized:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Confirm repository initialization
        run: test -s README.md
